default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: beloosmysql
  host: localhost
  

development:
  <<: *default
  database: development_todo_tutorial

test:
  <<: *default
  database: test_todo_tutorial

production:
  <<: *default
  database: production_todo_tutorial
